myproject/myapp_hw1/urls.py
from django.urls import path
from . import views

app_name = 'myapp_hw1'
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
]

myproject/myproject/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from myapp_hw3.views import index
from django.conf.urls.static import static

urlpatterns = [
    path('', index),
    path('admin/', admin.site.urls),
    path('hw1/', include('myapp_hw1.urls')),
    path('hw2/', include('myapp_hw2.urls')),
    path('hw3/', include('myapp_hw3.urls')),
    path('sem1/', include('myapp_sem1.urls')),
    path('lek1/', include('myapp_lek1.urls')),
    path('lek2/', include('myapp_lek2.urls')),
    path('lek3/', include('myapp_lek3.urls')),
    path('lek4/', include('myapp_lek4.urls')),
    path('lek6/', include('myapp_lek6.urls')),
    # path('__debug__/', include('debug_toolbar.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/myapp_hw1/views.py
from django.shortcuts import render
import logging

logger = logging.getLogger(__name__)

def index(request):
    logger.info('Index page accessed')
    return render(request, 'myapp_hw1/main.html')

def about(request):
    logger.info('Index page accessed1')
    return render(request, 'myapp_hw1/data.html')

myproject/myapp_hw1/templates/myapp_hw1/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>
        {% block title %}
        Мой сайт
        {% endblock %}
    </title>
</head>
<body>
    <div class="container-fluid">
        <ul class="nav nav-pills align-items-end nav nav-tabs">
            <li class="nav-item"><a href="{% url 'myapp_hw1:index' %}" class="nav-link">Основная</a></li>
            <li class="nav-item"><a href="{% url 'myapp_hw1:about' %}" class="nav-link">Данные</a></li>
        </ul>
        {% block content %}
            Страница не заполнена
        {% endblock %}
        <div class="row fixed-bottom modal-footer">
            <hr>
            <footer>Все права защищены &copy;</footer>
        </div>
    </div>
</body>
</html>

myproject/myapp_hw1/templates/myapp_hw1/data.html
{% extends 'base.html' %}

{% block title %}
    {{ super }} - {{ title }}
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <h1>Знакомьтесь, это Андрей - местный ИТ-волшебник и питонист-виртуоз!</h1>
        <p>Днем Андрей яростно покоряет вершины Python-разработки, с легкостью решая самые сложные задачи. Неудивительно, ведь этот парень с компьютерами на "ты" с самого детства!</p>
        <p>Но Андрей - далеко не скучный "зубрила". Стоит солнцу закатиться за горизонт, как он превращается в отчаянного искателя приключений и страстного путешественника. Его рабочее место - это весь необъятный мир, где он чувствует себя как рыба в воде.</p>
        <p>Андрей одинаково виртуозно управляется с Linux, Windows и MacOS. Он запросто находит общий язык и с серверами, и с мобильными устройствами. Этому ИТ-гуру покоряются любые технологии и программы - от простых скриптов до сверхсложных алгоритмов.</p>
        <p>Но самое удивительное в Андрее - это его неуемная жажда странствий. Стоит ему выйти за пределы офиса, как он тут же срывается в очередное захватывающее путешествие. Он с азартом покоряет горные вершины, ныряет в глубины океана и даже осваивает полеты на дельтаплане.</p>
        <p>Итак, перед вами универсальный ИТ-специалист и отчаянный путешественник, который никогда не сидит на месте. Этот человек-загадка постоянно находится в движении - и физическом, и умственном. Так что если вы хотите угнаться за Андреем, будьте готовы ко всему!</p>
    </div>
{% endblock %}

myproject/myapp_hw1/templates/myapp_hw1/main.html
{% extends 'base.html' %}
{% block title %}
    {{ super }} - {{ title }}
{% endblock %}

{% block content %}
    <div class="row">
        <h1>Добро пожаловать на мой веб-сайт!</h1>
        <p>Дорогие друзья, я с гордостью представляю вам мой первый веб-сайт, созданный с использованием мощного фреймворка Django.</p>
        <p>Этот проект стал для меня настоящим испытанием и захватывающим приключением в мир веб-разработки. Шаг за шагом я осваивал основы Django, учился создавать динамические страницы, работать с данными и настраивать серверную часть приложения.</p>
        <p>На этом сайте вы найдете простое, но искреннее приветствие всем, кто заглянул сюда. Это лишь начало моего пути в веб-разработке, но уже сейчас я чувствую, что этот опыт открывает передо мной бесконечные возможности для творчества и самосовершенствования.</p>
        <p>Я надеюсь, что мой энтузиазм и стремление к новым знаниям вдохновят вас на собственные проекты и открытия в мире программирования. Если у вас есть вопросы или предложения, не стесняйтесь обращаться ко мне - я всегда рад новому диалогу и совместному поиску решений.</p>
        <p>Спасибо, что посетили мой первый сайт. Это лишь начало большого пути, и я с нетерпением жду возможности поделиться с вами своими будущими достижениями!</p>
    </div>
{% endblock %}