myproject/myapp_hw1/urls.py
from django.urls import path
from . import views

app_name = 'myapp_hw1'
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
]

myproject/myapp_hw3/urls.py
from django.urls import path
from .views import all_orders, orders_by_days, product_cart, product_create, product_detail, index, all_product

app_name = 'myapp_hw3'
urlpatterns = [
    path('', index, name='index'),
    path('allorders/', all_orders, name='all_orders'),
    path('allproduct/', all_product, name='all_product'),
    path('product/', product_cart, name='product_cart'),
    path('product_create/', product_create, name='product_create'),
    path('products/<int:pk>/', product_detail, name='product_detail'),
    path('days/<int:user_id>/<int:days>', orders_by_days, name='orders_by_days'),
]

myproject/myproject/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from myapp_hw3.views import index
from django.conf.urls.static import static

urlpatterns = [
    path('', index),
    path('admin/', admin.site.urls),
    path('hw1/', include('myapp_hw1.urls')),
    path('hw2/', include('myapp_hw2.urls')),
    path('hw3/', include('myapp_hw3.urls')),
    path('sem1/', include('myapp_sem1.urls')),
    path('lek1/', include('myapp_lek1.urls')),
    path('lek2/', include('myapp_lek2.urls')),
    path('lek3/', include('myapp_lek3.urls')),
    path('lek4/', include('myapp_lek4.urls')),
    path('lek6/', include('myapp_lek6.urls')),
    # path('__debug__/', include('debug_toolbar.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>
        {% block title %}
        Мой сайт
        {% endblock %}
    </title>
</head>
<body>
    <div class="container-fluid">
        <ul class="nav nav-pills align-items-end nav nav-tabs">
            <li class="nav-item"><a href="{% url 'myapp_hw3:index' %}" class="nav-link">Основная</a></li>
            <li class="nav-item"><a href="{% url 'myapp_hw1:about' %}" class="nav-link">Данные</a></li>
        </ul>
        {% block content %}
            Страница не заполнена
        {% endblock %}
        <div class="row fixed-bottom modal-footer">
            <hr>
            <footer>ВСЕ права защищены &copy;</footer>
        </div>
    </div>
</body>
</html>