myproject/myapp_hw1/urls.py
from django.urls import path
from . import views

app_name = 'myapp_hw1'
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
]

myproject/myapp_hw3/urls.py
from django.urls import path
from .views import all_orders, orders_by_days, product_cart, product_create, product_detail, index, all_product

app_name = 'myapp_hw3'
urlpatterns = [
    path('', index, name='index'),
    path('allorders/', all_orders, name='all_orders'),
    path('allproduct/', all_product, name='all_product'),
    path('product/', product_cart, name='product_cart'),
    path('product_create/', product_create, name='product_create'),
    path('products/<int:pk>/', product_detail, name='product_detail'),
    path('days/<int:user_id>/<int:days>', orders_by_days, name='orders_by_days'),
]

myproject/myproject/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from myapp_hw3.views import index
from django.conf.urls.static import static

urlpatterns = [
    path('', index),
    path('admin/', admin.site.urls),
    path('hw1/', include('myapp_hw1.urls')),
    path('hw2/', include('myapp_hw2.urls')),
    path('hw3/', include('myapp_hw3.urls')),
    path('sem1/', include('myapp_sem1.urls')),
    path('lek1/', include('myapp_lek1.urls')),
    path('lek2/', include('myapp_lek2.urls')),
    path('lek3/', include('myapp_lek3.urls')),
    path('lek4/', include('myapp_lek4.urls')),
    path('lek6/', include('myapp_lek6.urls')),
    # path('__debug__/', include('debug_toolbar.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/myapp_hw3/models.py
from django.db import models
from django.core.validators import MinValueValidator



class User(models.Model):
    name = models.CharField(max_length=100, verbose_name='Имя клиента')
    email = models.EmailField(verbose_name='Почта')
    phone = models.CharField(max_length=12, verbose_name='Телефон')
    address = models.CharField(max_length=150, verbose_name='Адрес')
    date_registered = models.DateField(auto_now_add=True, verbose_name='Дата регистрации')

    class Meta:
        verbose_name = "Клиент"
        verbose_name_plural = "Клиенты"


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название товара')
    description = models.TextField(verbose_name='Описание')
    price = models.DecimalField(max_digits=8, decimal_places=2, validators=[MinValueValidator(0)], verbose_name='Цена')
    quantity_products = models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во')
    date_created = models.DateField(auto_now_add=True, verbose_name='Дата создания')
    image = models.ImageField(upload_to='products/', default='products/default.jpg', verbose_name='Изображение')

    # def __str__(self):
    #     return f'Name_product: {self.name}, Price: {self.price}, Balance(Kol-vo):{self.quantity_products}'

    class Meta:
        verbose_name = "Товар"
        verbose_name_plural = "Товары"


class Order(models.Model):
    customer = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Номер Заказа')
    products = models.ManyToManyField(Product)
    total_price = models.DecimalField(max_digits=8, decimal_places=2, verbose_name='Сумма заказа')
    date_ordered = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')

    class Meta:
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"

myproject/myapp_hw3/forms.py
from django import forms
import datetime


class ProductForm(forms.Form):
    name = forms.CharField(max_length=100)
    description = forms.CharField(widget=forms.Textarea)
    price = forms.DecimalField(max_digits=8, decimal_places=2, min_value=0)
    quantity_products = forms.IntegerField()
    date_created = forms.DateField(initial=datetime.date.today)
    image = forms.ImageField()

myproject/myapp_hw3/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Order, User, Product
from .forms import ProductForm
from django.utils import timezone
import logging
from django.core.files.storage import FileSystemStorage

logger = logging.getLogger(__name__)


def index(request):
    return render(request, "myapp_hw3/index.html")


def all_product(request):
    logger.info('Index page accessed')
    products = list(Product.objects.all())
    return render(request, 'myapp_hw3/all_product.html', {'products': products})


def all_orders(request):
    logger.info('Index page accessed')
    orders = list(Order.objects.all())
    return render(request, 'myapp_hw3/all_orders.html', {'orders': orders})


def orders_by_days(request, user_id, days):
    days_html = days
    user = get_object_or_404(User, pk=user_id)
    start_date = timezone.now() - timezone.timedelta(days=days)
    orders_user = Order.objects.filter(customer=user, date_ordered__gte=start_date)

    order_products = {}
    for order in orders_user:
        for product in order.products.all():
            if product not in order_products:
                order_products[product] = order.date_ordered
            else:
                order_products[product] = max(order_products[product], order.date_ordered)

    order_products = sorted(order_products.items(), key=lambda x: x[1], reverse=True)

    return render(request, f'myapp_hw3/orders_by_days.html', {
        'user': user,
        'order_products': order_products,
        'days_html': days_html
        })


def product_cart(request):
    # product = get_object_or_404(Product, pk=product_id)
    # return render(request, 'myapp_hw3/product_cart.html', {'product': product})
    product_id = request.GET.get('product_id')
    if product_id:
        product = get_object_or_404(Product, pk=product_id)
        return render(request, 'myapp_hw3/product_cart.html', {'product': product})

def product_create(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = Product(name=form.cleaned_data['name'],
                             price=form.cleaned_data['price'],
                             description=form.cleaned_data['description'],
                             image=form.cleaned_data['image'],
                             quantity_products=form.cleaned_data['quantity_products'],
                             date_created=form.cleaned_data['date_created'],
                            )
            fs = FileSystemStorage()
            fs.save(product.image.name, product.image)
            product.save()
            return render(request, 'myapp_hw3/product_cart.html', {'product': product})
    else:
        form = ProductForm()
    return render(request, 'myapp_hw3/product_create.html', {'form': form})


def product_detail(request, pk):
    product = Product.objects.get(pk=pk)
    return render(request, 'myapp_hw3/product_cart.html', {'product': product})

myproject/myapp_hw3/templates/myapp_hw3/all_orders.html
{% extends 'base.html' %}
{% block title %}
    {{ super }} - {{ title }}
{% endblock %}

{% block content %}
<h1>Список заказов</h1>
    <table>
        <thead>
            <tr>
                <th>Заказ №</th>
                <th>Покупатель</th>
                <th>Общая сумма</th>
                <th>Дата заказа</th>
                <th>Товары</th>
            </tr>
        </thead>
        <tbody>
            {% for order in orders %}
            {% if order.products.all %}
            <tr>
                <td>{{ order.id }}</td>
                <td>{{ order.customer.name }}</td>
                <td>{{ order.total_price }}</td>
                <td>{{ order.date_ordered }}</td>
                <td>
                    <table>
                        <thead>
                            <tr>
                                <th>Название</th>
                                <th>Цена</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for product in order.products.all %}
                            <tr>
                                <td>{{ product.name }}</td>
                                <td>{{ product.price }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </td>
            </tr>
            {% endif %}
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

myproject/myapp_hw3/templates/myapp_hw3/all_product.html
{% extends 'base.html' %}
{% block title %}
    {{ super }} - {{ title }}
{% endblock %}

{% block content %}
<h2>Список товаров:</h2>
<div class="row">
    {% for product in products %}
    <div class="col-4">
        <div class="card">
            <img src="{{ product.image.url }}" class="card-img-top" alt="Изображение продукта">
            <div class="card-body">
                <h5 class="card-title">{{ product.name }}</h5>
                <p class="card-text">{{ product.description }}</p>
                <p>Количество в наличии: {{ product.quantity_products }}</p>
                <p>Дата поставки: {{ product.date_created }}</p>
                <p>Цена: {{ product.price }}</p>
            </div>
        </div>
    </div>
    {% if forloop.counter|divisibleby:3 %}
</div>
<div class="row">
    {% endif %}
    {% endfor %}
</div>
{% endblock %}

myproject/myapp_hw3/templates/myapp_hw3/index.html
{% extends 'base.html' %}
{% block title %}
    {{ super }} - {{ title }}
{% endblock %}

{% block content %}
    <h2>Главная страница</h2>
    <h3>Ссылки для быстрого доступа:</h3>
    <ul>
        <li><a href="{% url 'myapp_hw3:all_product' %}">Показать список всех товаров</a></li>
        <li><a href="{% url 'myapp_hw3:all_orders' %}">Показать список заказов</a></li>
        <li><a href="{% url 'myapp_hw3:product_create' %}">Создать товар</a></li>
        <li>
            <form action="{% url 'myapp_hw3:product_cart' %}" method="get">
                <label for="product_id">Номер товара</label>
                <input type="number" id="product_id" name="product_id" required>
                <button type="submit">Перейти</button>
            </form>
        </li>
    </ul>
{% endblock %}

myproject/myapp_hw3/templates/myapp_hw3/orders_by_30days.html
{% extends 'base.html' %}
{% block title %}
    {{ super }} - {{ title }}
{% endblock %}

{% block content %}
    <h1>Товары пользователя {{ user.name }} из заказов за последние 30 дней </h1>
    {% for product, date_ordered in order_products %}
        <p>{{ product.name }} ({{ date_ordered }})</p>
    {% endfor %}
{% endblock %}

myproject/myapp_hw3/templates/myapp_hw3/orders_by_365days.html
{% extends 'base.html' %}
{% block title %}
    {{ super }} - {{ title }}
{% endblock %}

{% block content %}
    <h1>Товары пользователя {{ user.name }} из заказов за последние 365 дней </h1>
    {% for product, date_ordered in order_products %}
        <p>{{ product.name }} ({{ date_ordered }})</p>
    {% endfor %}
{% endblock %}

myproject/myapp_hw3/templates/myapp_hw3/orders_by_7days.html
{% extends 'base.html' %}
{% block title %}
    {{ super }} - {{ title }}
{% endblock %}

{% block content %}
    <h1>Товары пользователя {{ user.name }} из заказов за последние 7 дней </h1>
    {% for product, date_ordered in order_products %}
        <p>{{ product.name }} ({{ date_ordered }})</p>
    {% endfor %}
{% endblock %}

myproject/myapp_hw3/templates/myapp_hw3/orders_by_days.html
{% extends 'base.html' %}
{% block title %}
    {{ super }} - {{ title }}
{% endblock %}

{% block content %}
    <h1>Товары пользователя {{ user.name }} из заказов за последние {{ days_html }} дней </h1>
    {% for product, date_ordered in order_products %}
        <p>{{ product.name }} ({{ date_ordered }})</p>
    {% endfor %}
{% endblock %}

myproject/myapp_hw3/templates/myapp_hw3/orders_by_month.html
{% extends 'base.html' %}
{% block title %}
    {{ super }} - {{ title }}
{% endblock %}

{% block content %}
    <h1>Товары пользователя {{ user.name }} из заказов за последние 30 дней </h1>
    {% for product, date_ordered in order_products %}
        <p>{{ product.name }} ({{ date_ordered }})</p>
    {% endfor %}
{% endblock %}

myproject/myapp_hw3/templates/myapp_hw3/orders_by_year.html
{% extends 'base.html' %}
{% block title %}
    {{ super }} - {{ title }}
{% endblock %}

{% block content %}
    <h1>Товары пользователя {{ user.name }} из заказов за последние 365 дней </h1>
    {% for product, date_ordered in order_products %}
        <p>{{ product.name }} ({{ date_ordered }})</p>
    {% endfor %}
{% endblock %}

myproject/myapp_hw3/templates/myapp_hw3/product_cart.html
{% extends 'base.html' %}
{% block title %}
    {{ super }} - {{ title }}
{% endblock %}

{% block content %}
    <h2>Товар: {{ product.name }} </h2>
    <p>Описание: {{ product.description }}</p>
    <p>Количество в наличии: {{ product.quantity_products }}</p>
    <p>Дата поставки: {{ product.date_created }}</p>
    <p>Цена: {{ product.price }}</p>
    <img src="{{ product.image.url }}" alt="Изображение продукта">
{% endblock %}

myproject/myapp_hw3/templates/myapp_hw3/product_create.html
{% extends 'base.html' %}

{% block content %}
    <h2>Загрузить товар в каталог</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_div }}
        <div class="button-group">
            <button type="submit" class="btn btn-primary">Сохранить и перейти к товару</button>
            <a href="{% url 'myapp_hw3:all_orders' %}" class="btn btn-success">Просмотреть весь список товара</a>
        </div>
    </form>
{% endblock %}

myproject/myapp_hw3/templates/myapp_hw3/upload_image.html
{% extends 'base.html' %}

{% block content %}
    <h2>Загрузите изображение товара {{ product.name }}</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Загрузить</button>
    </form>
{% endblock %}